name = "skytools"

account_id = "${CLOUDFLARE_ACCOUNT_ID}"
workers_dev = true
compatibility_date = "2023-01-01"
minify = true

# Enable the Worker
main = "dist/server/worker.js"


# Only include necessary node_modules for Workers
[build]
#command = "pnpm workspace skutools-api build:server && pnpm build:server"
#command = "pnpm workspace skytools-api build:server"
#command = "cd server && pnpm build"
#command = "cd server && pnpm install && pnpm build"
command = "pnpm build:server"

#
# Define environment variables
[vars]
NODE_ENV = "production"
