tabWidth: 2
useTabs: false
semi: false
singleQuote: true
quoteProps: as-needed
trailingComma: es5
bracketSpacing: true
bracketSameLine: true
arrowParens: avoid
endOfLine: lf
htmlWhitespaceSensitivity: 'ignore'
vueIndentScriptAndStyle: true
singleAttributePerLine: false
