nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmAuthToken: 4A215D75-C7AD-40CF-B346-99D36A8D2961
    npmRegistryServer: "https://npm.fontawesome.com/"

packageExtensions:
  "@vueuse/core@*":
    peerDependencies:
      vue: "*"
  "@vueuse/shared@*":
    peerDependencies:
      vue: "*"
  eslint-plugin-nuxt@*:
    peerDependencies:
      eslint: "*"
  nuxt@*:
    peerDependencies:
      vite: "*"
