nodeLinker: node-modules
packageExtensions:
  "@vueuse/core@*":
    peerDependencies:
      vue: "*"
  "@vueuse/shared@*":
    peerDependencies:
      vue: "*"
  "eslint-plugin-nuxt@*":
    peerDependencies:
      eslint: "*"
  "nuxt@*":
    peerDependencies:
      vite: "*"