nodeLinker: node-modules
packageExtensions:
  "@vueuse/core@*":
    peerDependencies:
      vue: "*"
  "@vueuse/shared@*":
    peerDependencies:
      vue: "*"
  "eslint-plugin-nuxt@*":
    peerDependencies:
      eslint: "*"
  "nuxt@*":
    peerDependencies:
      vite: "*"
npmScopes:
  awesome.me:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "${FONTAWESOME_NPM_AUTH_TOKEN}"
npmRegistries:
  "https://npm.fontawesome.com/":
    npmAlwaysAuth: true
    npmAuthToken: "${FONTAWESOME_NPM_AUTH_TOKEN}"
