name: Deploy Workers

on:
  push:
    branches:
      - main
    paths:
      - 'app/server/**'
      - 'wrangler.toml'
      - '.github/workflows/deploy-workers.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'app/pnpm-lock.yaml'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.10.0

      - name: Install dependencies
        run: |
          pnpm install
          pnpm --filter skytools-api install --prod

      - name: Build server
        run: pnpm workers:build

      - name: Deploy to Cloudflare Workers
        run: pnpm workers:deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          NODE_ENV: "production"
        working-directory: ./app
